### ISSUE TITLE
Bump to strict-type v1.4 causes performance degradation

### ISSUE THREAD

**Issue by crisdut** [strict-types/strict-types#21]
Hi @dr-orlovsky,

I felt a degradation in encode and decode operations after bumping strict-type to 1.4, some operations were 5 to 10 times slower.

I made a comparative table of operations (using bitmask-core):

| function                     | strict-type 1.3.x | strict-type 1.4.x |
|------------------------|-----------|------------|
| issue contract                | 1s  | 10.46s       |
| import_contract        | 106ms     | 3.27s       |
| export contract         | 95ms       | 4.26s       |
| store_stock                | 25.41ms  | 1.46s       |

### **Test Steps**

**Bitmask Core (Source Code)**

* Branch Strict-Type 1.3 https://github.com/diba-io/bitmask-core/pull/253 (you can use this [unit test](https://github.com/diba-io/bitmask-core/tree/CD/re-issue/tests/rgb/unit/issue.rs))
* Branch Strict-Type 1.4 https://github.com/diba-io/bitmask-core/pull/255 (you can use this [unit test](https://github.com/diba-io/bitmask-core/tree/CD/re-issue-2/tests/rgb/unit/issue.rs))

**RGB (Source Code)**

* Branch Strict-Type 1.4 https://github.com/RGB-WG/rgb/commit/cd81a7b2846913b3eba89a7c9e6a3e359f2bd9d7 (issue operation or import operation)
* Branch Strict-Type 1.2 https://github.com/RGB-WG/rgb/commit/39480d706e390920cb2c3c79afcb7a61b92e9198 (issue operation or import operation)

I hope to help!

Thanks

**Comment by zoedberg** [comment]
This seems to be the same issue reported here https://github.com/RGB-WG/rgb/issues/20

**Comment by dr-orlovsky** [comment]
Good, it seems that you figured out the source of https://github.com/RGB-WG/rgb/issues/20

What can do that? Well, it is possible that this is caused by switching hashing algorithm from BLAKE3 to SHA256! The reason of the switch was to make Strict types more compatible with RGB - and also to remove BLAKE3 problem with some WASM implementations in browsers making it to panic.

**Comment by crisdut** [comment]
> This seems to be the same issue reported here [RGB-WG/rgb#20](https://github.com/RGB-WG/rgb/issues/20)

Oh, sorry @zoedberg, I ended up not seeing that there was already an open issue.

Thanks for letting me know.

**Comment by crisdut** [comment]
Hi @dr-orlovsky 

I think I found the issue:

Basically [this Ident encode implementation](https://github.com/strict-types/strict-encoding/compare/v2.3.0...master#diff-2751dfa03f93e1886409c140ad3aaedc9cd7ce2584803eba8c625e9d6e5b487eR133-R144) is causing the degradation, we need to optimize this check.

After rollback to the piece of code to `impl_strict_newtype!(Ident, STRICT_TYPES_LIB, "Dumb");`, the slowness is over.

Unfortunately, I can't act on it right now, but I'll try tomorrow.

Also, I didn't feel any difference between SHA2 and BLACK3 during my tests.

**Comment by cryptoquick** [comment]
How much data did you test it with? The performance improvement should only be obvious once it's used with larger pieces of data. I'd be curious of the performance difference at 16MB.

**Comment by crisdut** [comment]
> How much data did you test it with? The performance improvement should only be obvious once it's used with larger pieces of data. I'd be curious of the performance difference at 16MB.

Basically, I performed the creation of a single contract and 3 transfers, where each step I retrieved and saved the entire Stock.

This tests: https://github.com/diba-io/bitmask-core/blob/0621f95596a43f86692ebe831a4cf8deb884f7f0/tests/rgb/integration/transfers.rs#L850

But, I agree with you, I haven't done data-intensive testing. I will do.

**Comment by dr-orlovsky** [comment]
> Basically, [this transformation](https://github.com/strict-types/strict-encoding/compare/v2.3.0...master#diff-2751dfa03f93e1886409c140ad3aaedc9cd7ce2584803eba8c625e9d6e5b487eR140) cause the degradation, we need to optimize this check.

We can't "simply revert" the change since it is a bugfix and by reverting it we will re-introduce the bug of not serializing all type names and field names in RGB as a restricted sets of ASCII characters.

What the change does is that it basically checks that each character in a identifier names (which are type names, field names, enum variant names, state names, transition names etc) lies within the scope of ASCII char. That seems to be causing slowness.

I am looking how this check can be made faster.

**Comment by dr-orlovsky** [comment]
I did the profiling and can confirm that
a) the issue is unrelated to SHA256
b) it is the strict encoding of the arrays based on enums (like with restricted characters) which takes >95% of time of all of the operation

Stirct encoding called each time we compute `SchmaId`, so if we cache it we can improve the speed by four-five times. However I believe there can be other improvements and I think how we can solve the source of the problem

**Comment by dr-orlovsky** [comment]
Two PRs which should improve performance at the level of strict types system:
- https://github.com/strict-types/strict-encoding/pull/22
- https://github.com/strict-types/strict-encoding/pull/15

**Comment by dr-orlovsky** [comment]
I did the benchmarking; the first PR increases speed x1.5 fold, second - x10, when both combined - x15. Seems this should be enought
